variables:
  GIT_SUBMODULE_STRATEGY: normal


.build_template: &distro_build
  script:
    - meson _build
    - ninja -C _build install

stages:
   - flatpak
   - build


##################
# Fedora Rawhide #
##################

fedora:rawhide:
    image: fedora:rawhide
    stage: build

    before_script:
      - dnf install -y gcc meson ninja-build gettext gtk-doc glib2-devel gtk3-devel
        gnome-online-accounts-devel libpeas-devel evolution-data-server-devel
        rest-devel json-glib-devel

    <<: *distro_build
    only:
    - schedules
    - web
    - tags



################
# Ubuntu Devel #
################

ubuntu:devel:
    image: ubuntu:devel
    stage: build
    before_script:
    # Ubuntu requires running update to fetch metadata and find packges
    - apt update
    - apt install -y gcc meson gettext gtk-doc-tools libglib2.0-dev git libgtk-3-dev
                     libgoa-1.0-dev libpeas-dev libecal1.2-dev libedataserver1.2-dev
                     librest-dev libjson-glib-dev
    <<: *distro_build
    only:
    - schedules
    - web
    - tags



##################
# Flatpak Bundle #
##################

flatpak:master:
    image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:3.28
    stage: flatpak
    variables:
      DEVELOPMENT_FLATPAK_ID: "TodoDevel"

    script:
    # Print debug information
    - build-aux/ci/debug.sh environment
    - build-aux/ci/debug.sh git

    # Setup the current directory
    - build-aux/ci/setup.sh $DEVELOPMENT_FLATPAK_ID $CI_COMMIT_SHA

    # Build and generate the bundle
    - build-aux/ci/build-flatpak-bundle.sh $DEVELOPMENT_FLATPAK_ID

    artifacts:
        paths:
        - org.gnome.$DEVELOPMENT_FLATPAK_ID.flatpak
        expire_in: 3 days
    cache:
        paths:
        - .flatpak-builder/cache
